### PR TITLE
Async deco

### PR DESCRIPTION
**Pull request by sithmel**
Here's a candidate to a major release of reliable-get.
The main goal was to factoring out reusable logic into async-deco decorators: caching, fallback. This allowed to add the dedupe decorator and potentially others (like the "limit", "retry", "balance", having multiple caching levels and so on).

### CODE REVIEW

**Comment by gabceb** [comment]
I noticed you added a benchmark file. Can you share the perf gains if any with these changes over what we have?

I personally find the submitted code harder to understand   than the previous code (which may just caused due to the fact that is more functional programming-esque or that is just early and I'm reading this on my phone).

**Comment by sithmel** [comment]
The new benchmark file is a left-over of a rigged demo I created to showcase the dedupe decorator.
I should have probably removed it before doing the PR.

The only performance improvement was the dedupe decorator itself: https://github.com/sithmel/async-deco#dedupe
I don't really expect big improvements from it, using real data.

About the code: the current one is probably easy to understand as everything is laid out on a file.
But for the same reason, more than one functionality was entangled together and was more difficult to adding functionalities.
Here you can see caching, fallback and deduping as 3 separated but different decorators: https://github.com/tes/reliable-get/blob/async-deco/index.js#L23-L25

One of the part I like less is this big logger function: https://github.com/tes/reliable-get/blob/async-deco/index.js#L45. Especially because I am using it for changing the final output: https://github.com/tes/reliable-get/blob/async-deco/index.js#L101-L111
But I consider it a minor problem.

Happy to consider any suggestion ;-)

**Comment by sithmel** [comment]
Updated async-deco version and many fixes (especially to the logging).

**Comment by cliftonc** [comment]
Thanks @sithmel!

**Pull request merged**
