### PR TITLE
Pass through request options

### PR DESCRIPTION
**Pull request by avengerpenguin**
I've done this a few times when I have something wrapping request. Basically, we allow the options object passed in to be passed through untouched and `reliable-get` just sets some sensible defaults.

The use case for us is that we need to pass in SSL configuration around client certificates, but a user might want to set all sorts of things. It makes sense to not to have to pull out each bit a client might want to set and instead expose the full power of `request` to the caller.

### CODE REVIEW

**Comment by gabceb** [comment]
This looks good to me @avengerpenguin, thanks!

Do you mind adding a test for it? You can pass {qs: { test: 1 } } to the get method and have the stub server verify the url contains the test query param.

**Comment by avengerpenguin** [comment]
Ah, I was going to ask about that. I tried to write a test first, but couldn't figure out how to inspect the request as opposed to the response, so I threw it away. I'll try again later today, thanks.

**Comment by gabceb** [comment]
👍🏻 let me know if you need any help with it

**Comment by dmorgantini** [comment]
@gabceb @avengerpenguin do you guys need any help with this PR?

**Comment by gabceb** [comment]
Closed in favor of https://github.com/tes/reliable-get/pull/12 which is now available on npm

**Pull request closed without merging**
