### PR TITLE
Need to select the db from the redisConfig

### PR DESCRIPTION
**Pull request by doodlemoonch**
Explicitly select db from config, to avoid issues when using localhost with different dbs

### CODE REVIEW

**Comment by sithmel** [comment]
sorry for the late answer, I'll see if I can manage to implement that in the new codebase

**Comment by sithmel** [comment]
This is already been implemented for a while.
You only need to specify the db in the query string for redis connection as specified here:
https://github.com/NodeRedis/node_redis#rediscreateclient

**Comment by doodlemoonch** [comment]
Ha, this is an old one! Thanks @sithmel

**Comment by cliftonc** [comment]
Only ~3 years! :D

**Pull request closed without merging**
