### PR TITLE
Enabling to pass in options as a part of http request object

### PR DESCRIPTION
**Pull request by lalkhum**
- so that we can pass in Http options like qs while hitting iSite api

### CODE REVIEW

**Comment by gabceb** [comment]
Thanks @lalkhum. Can you add a quick note on the README to specify that the options object will be fully passed down to the request. Thanks!

A test passing qs would be also cool 😎

**Comment by lalkhum** [comment]
Will do @gabceb :)
In the mean time, I will close this PR for now to re-open it once it is ready.
Cheers

**Comment by gabceb** [comment]
Appreciate it @lalkhum 🙌🏻

**Comment by gabceb** [comment]
Btw you can keep pushing commits to your branch and GH will add them to the PR. No need to close this one. Just Fyi

**Comment by gabceb** [comment]
Good to go?

**Comment by lalkhum** [comment]
Yup.

**Comment by gabceb** [comment]
Very happy. Thanks @lalkhum

**Comment by lalkhum** [comment]
My pleasure @gabceb

**Comment by gabceb** [comment]
I'll push the new version to npm later today

**Comment by lalkhum** [comment]
Cool, thanks.

**Comment by lalkhum** [comment]
@gabceb A gentle reminder for pushing the new version to npm. Thanks.

**Comment by gabceb** [comment]
Sorry @lalkhum. We switched our npm account to an org and seem to have lost the ability to publish a module :man_facepalming: 

Working on it

**Comment by lalkhum** [comment]
Ah Ok. Thanks for letting me know.

**Comment by gabceb** [comment]
@lalkhum the new version is now published. Npmjs had incorrectly deleted our users and it caused all kind of headaches. Everything should be back to normal now

**Comment by lalkhum** [comment]
Sorry to hear about the problem you all have been through but it's good to hear that everything is normal now. Thanks again for letting me know. Appreciate it.

**Pull request merged**
