### PR TITLE
Support for dynamic caching keys.

### PR DESCRIPTION
**Pull request by ernestofreyreg**
Added a new config option: cache.dynamicCacheKeys as a function(key, options, next) to asynchronously change caching keys, based on context.

### CODE REVIEW

**Comment by gabceb** [comment]
Please leave spaces and new lines like they were initially and fix on a different PR + add tests for the new code.

I personally would prefer to have cacheKeys be a value or a sync function instead of having a new dynamicCacheKey prop. The way you use the default denymicCacheKey is a bit counter-intuitive IMO but ok with me if others like your approach.

**Comment by cliftonc** [comment]
Can someone explain what we're trying to do here?

**Comment by ernestofreyreg** [comment]
I am deleting this branch and PR, to move the functionality to compoxure
where it makes more sense.

We want to be able to create different caching keys based on the
combination of experiments running on a determined service/app.

For example: If we are running 2 experiments (exp1 and exp2) on
app-resource (RDP) each one with a control group (a) and two variants (b
and c) then we can use a set of cookies (__tesu, siteCountry, getCountry,
TESCookieUser, ...) and hash out users with those experiments (PlanOut.js
wrapper module-tes-experiments), so now we have a max of 9 combinations
(exp1_a_exp2_a, exp1_a_exp2_b, ..., exp2_c_exp2_c) Adding these to the
caching Key will allow us to keep caching while performing experiments on
apps/services.

We where reviewing this PR and the best way to put it is in compoxure, as a
middleware it has access to request => access to cookieset.

**Comment by gabceb** [comment]
👍🏻

**Pull request closed without merging**
